function [res] = cost_lie_single(u, delta_p_ij, delta_v_ij, params)

    res = dot(delta_p_ij, u) / norm(delta_p_ij) +...
            (dot(delta_v_ij, delta_p_ij)^2) / norm(delta_p_ij)^3 + ...
            (2 * params.amax * dot(delta_v_ij, delta_p_ij)) / ( norm(delta_p_ij) * sqrt(4 * params.amax * (norm(delta_p_ij) - params.Ds)) ) + ...
            norm(delta_v_ij)^2 / norm(delta_p_ij);
    res = -real(res);
end
